version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
